download a specific version of our helm charts, rather than just the …
wireapp/wire-server-deploy-networkless pull request #36
Opened 2020-07-20 12:50 UTC by julialongtin

…newest version.

2020-07-20 14:04 UTC, jschaul commented on vpc/ansible/group_vars/helm_charts.yml
> +  develop: no
nesting variables in ansible can lead to issues, especially if something is not defined (one needs to then first check if the parent variable is defined).

I'd prefer:

```yaml
helm_repo_version: 0.105.0
helm_repo_develop: false
helm_repo_url_base: "https://s3-eu-west-1.amazonaws.com/public.wire.com/"
helm_repo_url: "{{ helm_repo_url_base }}{% if helm_repo_develop %}charts-develop{% else %}charts{% endif %}
```

Then, you don't need two copy-pasted tasks on/off based on helm_repo_develop.

2020-09-02 08:48 UTC, julialongtin commented on vpc/ansible/group_vars/helm_charts.yml
> +  develop: no
we check to see if the parent variable is defined, in order to optionally use import_vars to pull in the vars.

2020-09-02 08:50 UTC, akshaymankar requested changes
Everything looks fine to my noob eyes except for a little indentation.

2020-09-02 08:50 UTC, akshaymankar commented on vpc/ansible/populate_helm_repo-tasks.yml
> +      helm pull --destination {{ offline_content_dir }}/helm_repository/charts --untar --untardir {{ offline_content_dir }}/helm_repository/charts {{ item.value.name }} --version {{ helm_repo.version
```suggestion
    else 
      rm -rf {{ offline_content_dir }}/helm_repository/charts/$CHARTNAME
      helm pull --destination {{ offline_content_dir }}/helm_repository/charts --untar --untardir {{ offline_content_dir }}/helm_repository/charts {{ item.value.name }} --version {{ helm_repo.version }}
```

That else was hidden otherwise

2020-09-02 09:01 UTC, akshaymankar approved these changes

2020-09-02 09:04 UTC, merged